<script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
<script src="{{ asset('web/js/jquery.min.js') }}"></script>
<script src="{{ asset('web/js/scrolloverflow.min.js') }}"></script>
<script src="{{ asset('web/js/jquery.youtubebackground.js') }}"></script>
<script src="{{ asset('web/js/jquery.fullpage.js') }}"></script>
<script src="{{ asset('web/js/TimelineMax.min.js') }}"></script>
<script src="{{ asset('web/js/TweenMax.min.js') }}"></script>
<script src="{{ asset('web/js/slick.js') }}"></script>
<script src="{{ asset('web/js/owl.carousel.js') }}"></script>
<script src="{{ asset('web/js/custom.js') }}"></script>
